/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package OOP11;

import javax.swing.JOptionPane;
import java.sql.SQLException;

/**
 *
 * @author sqmson
 */
public class FlightDetails extends javax.swing.JFrame {
    
//    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FlightDetails.class.getName());
    private final Connect con;
    private int flightId;
    /**
     * Creates new form FlightDetails
     */
    public FlightDetails(int flightId, Connect con) {
        this.flightId = flightId;
        this.con = con;
        
        initComponents();
        
        loadFlightDetails();
    }
    
    private void loadFlightDetails() {
        try {
            String sql = """
                SELECT f.FlightNumber, f.DepartureTime, f.ArrivalTime, f.Status,
                       a.Model AS AircraftModel, al.Name AS AirlineName,
                       dep.Name AS DepartureAirport, arr.Name AS ArrivalAirport
                FROM flights f
                JOIN aircrafts a ON f.AircraftID = a.AircraftID
                JOIN airlines al ON a.Airline = al.AirlineID
                JOIN airports dep ON f.DepartureAirportID = dep.AirportID
                JOIN airports arr ON f.ArrivalAirportID = arr.AirportID
                WHERE f.FlightID = ?
            """;

            con.pst = con.con.prepareStatement(sql);
            con.pst.setInt(1, flightId);
            con.rs = con.pst.executeQuery();

            if (con.rs.next()) {
                lblAirline.setText("Airline: " + con.rs.getString("AirlineName"));
                lblAircraft.setText("Aircraft: " + con.rs.getString("AircraftModel"));
                lblRoute.setText("Route: " + con.rs.getString("DepartureAirport") + " → " + con.rs.getString("ArrivalAirport"));
                lblTimes.setText("Times: " + con.rs.getString("DepartureTime") + " → " + con.rs.getString("ArrivalTime"));
                lblStatus.setText("Status: " + con.rs.getString("Status"));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error loading flight details: " + e.getMessage());
        }
    }
    
    private void handleBooking() {
        String selectedClass = cmbClass.getSelectedItem().toString();
        JOptionPane.showMessageDialog(this, 
            "Booking started for Flight ID " + flightId + "\nClass: " + selectedClass + "\nProceeding to payment...");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAirline = new javax.swing.JLabel();
        lblAircraft = new javax.swing.JLabel();
        lblTimes = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        lblRoute = new javax.swing.JLabel();
        cmbClass = new javax.swing.JComboBox<>();
        btnBook = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblAirline.setText("Airline: ");

        lblAircraft.setText("Aircraft: ");

        lblTimes.setText("Times:");

        lblStatus.setText("Class");

        lblRoute.setText("Route");

        cmbClass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnBook.setText("Book Ticket");
        btnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Required Information");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAirline, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAircraft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTimes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblRoute, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmbClass, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBook)
                                .addGap(66, 66, 66)
                                .addComponent(btnCancel)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(178, Short.MAX_VALUE)
                .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblAirline)
                .addGap(24, 24, 24)
                .addComponent(lblAircraft)
                .addGap(24, 24, 24)
                .addComponent(lblTimes)
                .addGap(18, 18, 18)
                .addComponent(lblRoute)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBook)
                    .addComponent(btnCancel))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookActionPerformed
        // TODO add your handling code here:
        handleBooking();
    }//GEN-LAST:event_btnBookActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new FlightDetails().setVisible(true));
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBook;
    private javax.swing.JButton btnCancel;
    private javax.swing.JComboBox<String> cmbClass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAircraft;
    private javax.swing.JLabel lblAirline;
    private javax.swing.JLabel lblRoute;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTimes;
    // End of variables declaration//GEN-END:variables
}
