/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Admin;

import javax.swing.ImageIcon;
import javax.swing.UnsupportedLookAndFeelException;
/**
 *
 * @author Alfie
 */
public class AdminMenu extends javax.swing.JFrame {
    public int userId;
    /**
     * Creates new form MenuFrame
     */
    public AdminMenu() {
        initComponents();
        setTitle("Admin Dashboard");
        setLocationRelativeTo(null);
        
        try {
            // Load the image from resources
            ImageIcon icon = new ImageIcon(getClass().getResource("/assets/rocker-sta-RSYBi_1fhfM-unsplash.jpg"));
            // Scale the image to desired dimensions (e.g., 64x64)
            java.awt.Image img = icon.getImage();
            java.awt.Image scaledImg = img.getScaledInstance(96,96, java.awt.Image.SCALE_SMOOTH);
            btnAircraft.setIcon(new ImageIcon(scaledImg));
            
            ImageIcon icon1 = new ImageIcon(getClass().getResource("/assets/muhammad-ahmad-L2gg0LZ-we8-unsplash.jpg"));
            // Scale the image to desired dimensions (e.g., 64x64)
            java.awt.Image img1 = icon1.getImage();
            java.awt.Image scaledImg1 = img1.getScaledInstance(96,96, java.awt.Image.SCALE_SMOOTH);
            btnAirline.setIcon(new ImageIcon(scaledImg1));
            
            ImageIcon icon2 = new ImageIcon(getClass().getResource("/assets/matthew-pearce-hZ0fK4q9Aw0-unsplash.jpg"));
            // Scale the image to desired dimensions (e.g., 64x64)
            java.awt.Image img2 = icon2.getImage();
            java.awt.Image scaledImg2 = img2.getScaledInstance(96,96, java.awt.Image.SCALE_SMOOTH);
            btnLogout.setIcon(new ImageIcon(scaledImg2));
        } catch (Exception e) {
            System.out.println("Icon not found: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        lblName = new javax.swing.JLabel();
        btnAirline = new javax.swing.JButton();
        btnAircraft = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("jRadioButtonMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Airport Management-Main Menu");
        setSize(new java.awt.Dimension(600, 400));

        lblName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName.setText("Admin Dashboard");

        btnAirline.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        btnAirline.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/muhammad-ahmad-L2gg0LZ-we8-unsplash.jpg"))); // NOI18N
        btnAirline.setText("Aircrafts");
        btnAirline.setBorder(null);
        btnAirline.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAirline.setMaximumSize(new java.awt.Dimension(7360, 4941));
        btnAirline.setMinimumSize(new java.awt.Dimension(7360, 4941));
        btnAirline.setPreferredSize(new java.awt.Dimension(64, 64));
        btnAirline.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAirline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAirlineActionPerformed(evt);
            }
        });

        btnAircraft.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        btnAircraft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/rocker-sta-RSYBi_1fhfM-unsplash.jpg"))); // NOI18N
        btnAircraft.setText("Airlines");
        btnAircraft.setBorder(null);
        btnAircraft.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAircraft.setPreferredSize(new java.awt.Dimension(64, 64));
        btnAircraft.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/airplane.png"))); // NOI18N
        btnAircraft.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAircraft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAircraftActionPerformed(evt);
            }
        });

        btnLogout.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/matthew-pearce-hZ0fK4q9Aw0-unsplash.jpg"))); // NOI18N
        btnLogout.setText("Airports");
        btnLogout.setBorder(null);
        btnLogout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogout.setMaximumSize(new java.awt.Dimension(7360, 4941));
        btnLogout.setMinimumSize(new java.awt.Dimension(7360, 4941));
        btnLogout.setPreferredSize(new java.awt.Dimension(64, 64));
        btnLogout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnAircraft, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAirline, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAircraft, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAirline, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(152, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Airports().setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnAirlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAirlineActionPerformed
        // TODO add your handling code here:
        Airlines f = new Airlines();
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAirlineActionPerformed

    private void btnAircraftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAircraftActionPerformed
        // TODO add your handling code here:
        Aircrafts a = new Aircrafts();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAircraftActionPerformed
  
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException ex) {
            System.out.println("Look and feel not set: " + ex.getMessage());
        }
        java.awt.EventQueue.invokeLater(() -> {
            new AdminMenu().setVisible(true);
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAircraft;
    private javax.swing.JButton btnAirline;
    private javax.swing.JButton btnLogout;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JLabel lblName;
    // End of variables declaration//GEN-END:variables
}
