/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Passengers;

import Public.Login;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Alfie
 */
public class MenuFrame extends javax.swing.JFrame {

    /**
     * Creates new form MenuFrame
     */
    public MenuFrame() {
        initComponents();
        setTitle("Airport Management-Main Menu");
        setLocationRelativeTo(null);
        
        try {
            // Load the image from resources
            ImageIcon icon = new ImageIcon(getClass().getResource("/assets/airplane.png"));
            // Scale the image to desired dimensions (e.g., 64x64)
            java.awt.Image img = icon.getImage();
            java.awt.Image scaledImg = img.getScaledInstance(32, 32, java.awt.Image.SCALE_SMOOTH);
            btnPassengers.setIcon(new ImageIcon(scaledImg));
            
            ImageIcon icon1 = new ImageIcon(getClass().getResource("/assets/ticket.png"));
            // Scale the image to desired dimensions (e.g., 64x64)
            java.awt.Image img1 = icon1.getImage();
            java.awt.Image scaledImg1 = img1.getScaledInstance(32, 32, java.awt.Image.SCALE_SMOOTH);
            btnTickets.setIcon(new ImageIcon(scaledImg1));
            
            ImageIcon icon2 = new ImageIcon(getClass().getResource("/assets/logout.png"));
            // Scale the image to desired dimensions (e.g., 64x64)
            java.awt.Image img2 = icon2.getImage();
            java.awt.Image scaledImg2 = img2.getScaledInstance(32, 32, java.awt.Image.SCALE_SMOOTH);
            btnLogout.setIcon(new ImageIcon(scaledImg2));
        } catch (Exception e) {
            System.out.println("Icon not found: " + e.getMessage());
        }
        
//        btnPassengers.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
//        btnPassengers.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        lblName = new javax.swing.JLabel();
        btnTickets = new javax.swing.JButton();
        btnPassengers = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        MnFile = new javax.swing.JMenu();
        mniExit = new javax.swing.JMenuItem();
        MnHelp = new javax.swing.JMenu();
        mniAbout = new javax.swing.JMenuItem();

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("jRadioButtonMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Airport Management-Main Menu");
        setSize(new java.awt.Dimension(600, 400));

        lblName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName.setText("Welcome to the Airport Management System ");

        btnTickets.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        btnTickets.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/ticket.png"))); // NOI18N
        btnTickets.setText("My Tickets");
        btnTickets.setBorder(null);
        btnTickets.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTickets.setPreferredSize(new java.awt.Dimension(64, 64));
        btnTickets.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTickets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTicketsActionPerformed(evt);
            }
        });

        btnPassengers.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        btnPassengers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/airplane.png"))); // NOI18N
        btnPassengers.setText("Browse Flights");
        btnPassengers.setBorder(null);
        btnPassengers.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPassengers.setPreferredSize(new java.awt.Dimension(64, 64));
        btnPassengers.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/airplane.png"))); // NOI18N
        btnPassengers.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPassengers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPassengersActionPerformed(evt);
            }
        });

        btnLogout.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logout.png"))); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.setBorder(null);
        btnLogout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogout.setPreferredSize(new java.awt.Dimension(64, 64));
        btnLogout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        MnFile.setText("File");

        mniExit.setText("Exit");
        mniExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniExitActionPerformed(evt);
            }
        });
        MnFile.add(mniExit);

        jMenuBar1.add(MnFile);

        MnHelp.setText("Help");

        mniAbout.setText("About");
        mniAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAboutActionPerformed(evt);
            }
        });
        MnHelp.add(mniAbout);

        jMenuBar1.add(MnHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(btnPassengers, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTickets, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPassengers, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTickets, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnTicketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTicketsActionPerformed
        // TODO add your handling code here:
        TicketsFrame Tickets = new TicketsFrame();
        Tickets.setVisible(true);
                this.dispose();
    }//GEN-LAST:event_btnTicketsActionPerformed

    private void btnPassengersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPassengersActionPerformed
        // TODO add your handling code here:
        PassengersFrame Passengers = new PassengersFrame();
        Passengers.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPassengersActionPerformed

    private void mniExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mniExitActionPerformed

    private void mniAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAboutActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"ALFIE SAFE TRAVELS");
    }//GEN-LAST:event_mniAboutActionPerformed

    /**
     * @param args the command line arguments
     */
    public  static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MnFile;
    private javax.swing.JMenu MnHelp;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPassengers;
    private javax.swing.JButton btnTickets;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JLabel lblName;
    private javax.swing.JMenuItem mniAbout;
    private javax.swing.JMenuItem mniExit;
    // End of variables declaration//GEN-END:variables
}
